FROM adoptopenjdk/openjdk8
ADD target/bankbarrel-ru.shanalotte.jwt.provider.serviceregistry-2.6.7.jar /home
WORKDIR ["/home"]
CMD ["java", "-jar", "/home/bankbarrel-ru.shanalotte.jwt.provider.serviceregistry-2.6.7.jar"]
EXPOSE 8181